# Generated by Django 4.2 on 2026-02-13
# Add database indexes for commonly filtered fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0195_EE_permissions'),
    ]

    operations = [
        # Inventory.kind - filtered for smart/constructed inventories
        migrations.AlterField(
            model_name='inventory',
            name='kind',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Hosts have a direct link to this inventory.'),
                    ('smart', 'Hosts for inventory generated using the host_filter property.'),
                    ('constructed', 'Parse list of source inventories with the constructed inventory plugin.'),
                ],
                db_index=True,
                default='',
                help_text='Kind of inventory being represented.',
                max_length=32,
            ),
        ),
        # InventorySource.source - used in inventory source filtering
        migrations.AddIndex(
            model_name='inventorysource',
            index=models.Index(fields=['source'], name='main_invento_source_idx'),
        ),
        # UnifiedJob.status - used in cache_timeout_blocked and many query filters
        # Note: Job/WorkflowJob inherit status via multi-table inheritance from UnifiedJob
        migrations.AddIndex(
            model_name='unifiedjob',
            index=models.Index(fields=['status'], name='main_uj_status_idx'),
        ),
    ]
