# Generated by Django 4.2 on 2026-04-05
# Drift Detection models: HostFactSnapshot, DriftDetection, DriftAlertRule, DriftAlert

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0197_eda_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # HostFactSnapshot
        migrations.CreateModel(
            name='HostFactSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('facts', models.JSONField(default=dict, help_text='Full ansible_facts dictionary at capture time.')),
                ('facts_hash', models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of sorted JSON facts for quick equality check.', max_length=64)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_snapshots', to='main.host')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_snapshots', to='main.job')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_snapshots', to='main.inventory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization')),
            ],
            options={
                'ordering': ('-captured_at',),
                'app_label': 'main',
            },
        ),
        migrations.AddIndex(
            model_name='hostfactsnapshot',
            index=models.Index(fields=['host', '-captured_at'], name='main_hostfa_host_id_captur_idx'),
        ),
        migrations.AddIndex(
            model_name='hostfactsnapshot',
            index=models.Index(fields=['job', 'host'], name='main_hostfa_job_id_host_id_idx'),
        ),

        # DriftDetection
        migrations.CreateModel(
            name='DriftDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('packages', 'Packages'), ('services', 'Services'), ('users_groups', 'Users & Groups'), ('network', 'Network / Ports'), ('mounts', 'Mounts / Filesystems'), ('kernel', 'Kernel Parameters'), ('other', 'Other')], default='other', max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=16)),
                ('fact_path', models.CharField(help_text='Dot-delimited path to the changed fact.', max_length=512)),
                ('summary', models.CharField(blank=True, default='', max_length=1024)),
                ('detail', models.JSONField(default=dict, help_text='Structured diff: {before, after, diff_type}.')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_detections', to='main.host')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventory')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization')),
                ('snapshot_before', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drifts_before', to='main.hostfactsnapshot')),
                ('snapshot_after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drifts_after', to='main.hostfactsnapshot')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drift_detections', to='main.job')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-detected_at',),
                'app_label': 'main',
            },
        ),
        migrations.AddIndex(
            model_name='driftdetection',
            index=models.Index(fields=['host', '-detected_at'], name='main_driftd_host_id_detect_idx'),
        ),
        migrations.AddIndex(
            model_name='driftdetection',
            index=models.Index(fields=['-detected_at'], name='main_driftd_detecte_idx'),
        ),
        migrations.AddIndex(
            model_name='driftdetection',
            index=models.Index(fields=['category'], name='main_driftd_categor_idx'),
        ),
        migrations.AddIndex(
            model_name='driftdetection',
            index=models.Index(fields=['severity'], name='main_driftd_severit_idx'),
        ),

        # DriftAlertRule
        migrations.CreateModel(
            name='DriftAlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('host_filter', models.CharField(blank=True, default='', help_text='Host name pattern (fnmatch). Empty = all hosts.', max_length=512)),
                ('categories', models.JSONField(blank=True, default=list, help_text='List of drift categories to match. Empty = all.')),
                ('severity_min', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('threshold_count', models.PositiveIntegerField(default=1, help_text='Minimum drift items to trigger alert.')),
                ('threshold_window_minutes', models.PositiveIntegerField(default=60, help_text='Time window in minutes to count drift items.')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30, help_text='Minimum minutes between alerts from this rule.')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drift_alert_rules', to='main.organization')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inventory')),
                ('notification_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.notificationtemplate')),
            ],
            options={
                'ordering': ('name',),
                'app_label': 'main',
                'unique_together': {('organization', 'name')},
            },
        ),

        # DriftAlert
        migrations.CreateModel(
            name='DriftAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_rule_name', models.CharField(blank=True, default='', max_length=512)),
                ('drift_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notification_error', models.TextField(blank=True, default='')),
                ('alert_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='main.driftalertrule')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.host')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.organization')),
            ],
            options={
                'ordering': ('-created',),
                'app_label': 'main',
            },
        ),
    ]
